### ISSUE TITLE
Modifying config `mailInit.py` makes untracked changes

### ISSUE THREAD

**Issue by anqur** [AuthurExcalbern/Violet#1]
Configuration file `mailInit.py` should not be one of the source files, for it induces the contributors to pull their requests accidentally with their private data.

**Comment by AuthurExcalbern** [comment]
Thank you for your reminding.
I will add `mailInit.py` to `.gitignore`.

**Comment by anqur** [comment]
Alternatively, you can read them out of a config file by using `configparser` to be language-agnostic. E.g.

```
[email]
popServerName=
popUserName=
smtpServerName=
sender=
mailPassWd=
saveMailFile=
codingFetch=
```

**Comment by AuthurExcalbern** [comment]
This is a really good way.
I will update the project tomorrow.
Thanks for your teaching
